name: Document PR Comments

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  document-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyYAML
        
    - name: Run Python script
      run: python generate_comments_yaml.py
      env:
         GITHUB_REPOSITORY: ${{ github.repository }}
         GITHUB_EVENT_NUMBER: ${{ github.event.pull_request.number }}
         GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    

